version: "3.3"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://bett:Bett123456@matxiotdb.c36k8kooes7j.me-central-1.rds.amazonaws.com/matxiotdbdev
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=bett
      - POSTGRES_PASSWORD=Bett123456
      - POSTGRES_DB=matxiotdbdev

volumes:
  pgdata:
